### ISSUE TITLE
Create a kubernetes cluster - deploy these helm charts & from that create an OVA

### ISSUE THREAD

**Issue by dtollaku** [k8-proxy/icap-infrastructure#17]
Create a kubernetes cluster - deploy these helm charts & from that create an OVA much the same as when the Adaptation cluster charts were taken and deployed and an OVA created.
All the helm charts which point to built containers live here: https://github.com/filetrust/icap-infrastructure
filetrust/icap-infrastructure
Specifically the admin cluster https://github.com/filetrust/icap-infrastructure/tree/main/administration
The focus just needs to be on making a quick pathway of taking the latest helm charts for the clusters and deploying and creating an OVA

**Comment by dtollaku** [comment]
New cluster for management UI, that we need to have on a OVA.

**Comment by azopat** [comment]
I pretty much have a good picture about how it works. I confirm that it can run on a seperate cluster along with transaction service api and policy management api. But i think we may have an issue:  On the schema we saw during the call, we could see that there was one central point connecting both. That central point is a transaction store where transactions are logged by adaptation service from cluster 1 and they will be picked by transaction api on cluster 2. That file share must be an azure share, we can’t workaround it with local disk as we did last time, because it’s not a persistent volume, it’s a storage account. So i just need to clarify that this setup has one dependency with azure file share. Can we all agree that ? if yes i can create a file share on azure with my account and finish the setup. i think the person deploying the ova should have to do it as well or we will use the same fileshare for all OVAs. Let me know. I deployed UI here http://91.109.25.77:8086/

**Comment by mahnouman** [comment]
Hello @azopat , just to overcome the Azure issue, please point here as a comment to this topic, the code to be modified, where is is located (Which Repositories),  so that I refer the developer to this comment and he know where the modifications are needed, I assume it will be multiple components and repositories.

**Comment by azopat** [comment]
Here 
https://github.com/filetrust/transaction-event-api/blob/develop/TransactionEventApi/Startup.cs#L77
Basically he need to search were is used TransactionStoreConnectionStringCsv , because that is the connection string to azure share

**Comment by mohitsengarr** [comment]
Hi @azopat @mahnouman I have done the changes for this , however where I have to checkin or open pull request? should I fork and open directly in this repo https://github.com/filetrust/transaction-event-api?

**Comment by mahnouman** [comment]
Hello @azopat do your comment still valid? considering updates to upstream since the comment was made?
Also @mohitsengarr I forked the repo for you if you need to work with:
https://github.com/k8-proxy/transaction-event-api

**Comment by azopat** [comment]
@mahnouman  i don't think we need this anymore. everything now works out of the box. no nneed to have custom code anymore. also the architecture has changed. so definitely not valid anymore
